### ISSUE TITLE
About isBrowser

### ISSUE THREAD

**Issue by arthurzoubin** [tomatau/breko-hub#127]
export const isBrowser = typeof global !== 'undefined'
I find this in predicates.js file.
But i think global exists in browser, sometimes it is the same as window.
What's the matter?

**Comment by tomatau** [comment]
There's been a fix in place already for this. It's a known bug!

Check current master:

```js
export const isBrowser = process.env.APP_ENV === 'browser'
```

https://github.com/tomatau/breko-hub/blob/master/src/config/webpack.base.config.js#L39
