### ISSUE TITLE
Store as global for server-side?

### ISSUE THREAD

**Issue by ntucker** [tomatau/breko-hub#13]
Is it just me or is the redux store global, so every request from one use for one session will affect the initial store state sent to client for others?

**Comment by ntucker** [comment]
Looks like you fixed that recently. Did you also fix the part where it didn't wait for the promise to resolve from fetcher before it rendered the app?

**Comment by tomatau** [comment]
That was a crappy mistake by me in an initial refactor when trying to sort out middleware. But it's sorted now. I'm not sure why the fetcher wouldn't complete before it rendered the app. There's an example in BarRoute for ensuring a promise action is complete before the initial SSR too.

Regarding global stores. There's also a socketStore that gets created for handling socket broadcasts using redux-via. This store is purposefully separate as it has to stay global for all sessions. I try to just use it as a purely a broadcaster and avoid giving it any state.

**Comment by ntucker** [comment]
The part of my comment about fetcher not completing I removed because I realized I had broken it by not using Promise.all() when I did multiple promises in fetcher (not returning promise means it has nothing to wait for)
