### ISSUE TITLE
Use piping instead of writing your own code using chokidar

### ISSUE THREAD

**Issue by ntucker** [tomatau/breko-hub#15]
https://www.npmjs.com/package/piping

**Comment by tomatau** [comment]
I looked into piping when first starting this repo. The problems I had were: 
- It uses workers to manage the code when I'm just deleting the cache.
- I would have less control over memory leaks and refreshing the assets layer.

Can you make a branch that shows the benefits here? As I'm not sold but am definitely open to see how this could be an improvement.

**Comment by ntucker** [comment]
Hmm, I just thought it would be cleaner. Since it's only used for development worrying about memory leaks and such seems insignificant to development ease. I am not a fan of having huge boilerplates as improvements are hard to integrate once you branch off. Perhaps you could provide a library encapsulation of your improved method here?

The problem is when you make fixes/improvements here, it's hard to know every file touched to keep up to date.

**Comment by tomatau** [comment]
I understand that concern and it does make sense. I'm trying to stick to semver where possible -- but I'll be doing a fair bit of work when I get the chance in the coming weeks to add a lot of stuff.  I'm currently working on trying to get a nice setup for unit, functional and acceptance tests to cover the full codebase.

Also, I haven't touched the hot reload stuff for a good long while now so don't think moving it to a library would help with maintaining updates.

Would it be more useful for me to maintain a better CHANGELOG for version updates? That way it would be easier to see what's been improved or changed.

NB: memory leaks have hit me with dev before (koa-webpack-middleware) in other projects as they can suddenly eat through a system after an hour of hot-reloading. Definitely want to stay clear of them ;)
