### ISSUE TITLE
Mocha doesn't terminate

### ISSUE THREAD

**Issue by underscoredam** [tomatau/breko-hub#256]
Mocha doesn't terminate during integration test run using `./scripts/test/int.sh`, and suspect this because the mocha developers decided to change the mocha termination behavior starting v4.0.0. [This answer](https://stackoverflow.com/a/46759250/1807809) explains it. Should we add the `--exit` flags to `int.sh` and `unit.sh`? (Please do note that `unit.sh` is terminating however)

Configuration: 
```
mocha (global): 5.2.0
node: v10.7.0
```

**Comment by tomatau** [comment]
Oh hey! So sorry I'm super busy at the moment, hoping to go all out on this boilerplate within the next month once I've caught up in other areas and then will get on this error! I'm surprised you're seeing this as the latest master worked fine for me and in CI, it might be a node 10 issue. I've put off upping to node 10 until it goes LTS in October.

**Comment by tomatau** [comment]
Hi, I can't reproduce this in node 10
