### ISSUE TITLE
Preloading data from backend before SSR

### ISSUE THREAD

**Issue by believer-ufa** [tomatau/breko-hub#299]
Sorry, but i did not understand. I trying launch boilerplate in production mode, but even in it it do not preloading "bar" module data.

Boilerplate doesn't provide preloading data from api before SSR render, right?)

Strange, as i see, many boilerplates don't care about it, but without rendering data from backend on SSR - it does not work completely isomorphic.

**Comment by tomatau** [comment]
That's right I don't bake in pre-loading to the boilerplate as the code would be more difficult for a developer trying to understand.

You can add it yourself though with these steps:

1. Make an array of route config objects which contain the props you give to `<Route` for that route and a function called `preload(){` that returns a promise.
2. Use this array of routes in the SSR, call any appropriate `preload()` functions with appropriate arguments.
3. If the preload functions fire actions, the data would be loaded into the server side redux store ready for render.

In my experience, server side data loading isn't ideal.

Many times when distributing a website to a large user base, I would rather cache the server response so I can serve the users without hitting my server so often. To put user specific data in the server response, it makes this caching much more difficult. The same applies to serving different languages!

I'd suggest the PRPL pattern.

**Comment by believer-ufa** [comment]
Sorry for long answer - just hard working week.

Thanks for answer) Generally today i searching on best SSR realization in world for React. Thanks for explaining of one of approaches with routes - i'll remember this.

About SSR as isn't ideal approach - unfortunately, many search crawlers working very poor with websites that need JS to get full content of document, especially in async cases. So, i think you know that every request on server makes your app into asynchronous apps. 

While i work on one of my projects, we got a lot of problems with seo even with SSR 😂.. For example, you know what google search engine still uses [41 version of chrome engine](https://developers.google.com/search/docs/guides/rendering) on their Search bot? If your website working incorrectly on Chrome 41 - you may have problems with seo.

Annother problems with apps wirhout SSR - is async calls problem, as i said above. You can read about it [there](https://blog.pusher.com/seo-react-fetch-as-google/), for example.

So, today for me, I am almost fully approved on the following conclusions:

1. If you are working on website that need to be found though search enginges and if it fetching data from server on loading - you need SSR. It is necessary, no exceptions.

2. Your website must work only with ES5 javascript code. Because even Google [doesn't support ES6](https://developers.google.com/search/docs/guides/rendering#es6) on their search engine. I don't think that other engines working better )

**Comment by tomatau** [comment]
Are you happy with the solution for data fetching and I can close this issue?

**Comment by believer-ufa** [comment]
As you wish) Sure your can close)
