### ISSUE TITLE
How to edit the expected server-side state?

### ISSUE THREAD

**Issue by marclar** [tomatau/breko-hub#301]
Hi - I added a redux store called `auth`, and now the test `Server Side Render -> renders initial state from store` is failing. I see that the rendered state contains the key `auth` along with the initial state of the reducer, but the expected state does not contain this key.

I've been looking all over the repo to figure out where the expected state is created but I'm a bit lost. Any pointers?

Thanks!

**Comment by tomatau** [comment]
There's a stub store in the test that's used to generate the expected state

https://github.com/tomatau/breko-hub/blob/master/test/integration/server/server-render.test.js#L151-L158

You can change the test to dispatch actions on the stubStore that mimick what you expect the window.__INITIAL_STATE__ to be output as

**Comment by marclar** [comment]
Thanks, Thomas - so the `INITIAL_STATE` isn't populated at all, is that correct? I think my confusion comes from the assumption that it'd be created by merging each reducer's initial state.

**Comment by tomatau** [comment]
Umm, the initial state is always being populated! Can you show me some code or error messages because I'm not sure what I'm dealing with here

**Comment by marclar** [comment]
I have quite a bit of customization already, so I don't have a standalone repo on-hand, but here are what I believe are the relevant files:

https://gist.github.com/marclar/82d4b651023ace43568150636e2b7729

**Comment by tomatau** [comment]
By default the function creating the store in the tests is the same as the function creating the store in the app so the new auth reducer's initial state should be present in both

**Comment by marclar** [comment]
So weird. I've disabled the test for now; thanks for the info...
