### ISSUE TITLE
Is it ok using babel-register for production?

### ISSUE THREAD

**Issue by fishmacs** [tomatau/breko-hub#31]
Hi, I stumbled on your boilerplate and found it is a very good start point to a react-babel-koa project, thanks!
And I got a little confused after I had found babel-register used heavily, I think Babel guys do not agree use it for production:

[https://github.com/babel/example-node-server/issues/13](https://github.com/babel/example-node-server/issues/13)
[babel-handbook](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/user-handbook.md#toc-babel-register)

**Comment by tomatau** [comment]
Hi @fishmacs - glad you found it useful!

So when I started this project only the `babel-node` command was clearly discouraged and after looking at many other popular boilerplates, they also use the `babel-register` runtime in their production servers -- but still... it would be better to remove this runtime compilation on the server start command for production.

One thing, I wouldn't say we used it heavily in breko hub, it's just one file that uses it for the start command!

Anyway!.. :)

How to solve this -- it would be fairly straight forward for you to build the `./scripts/start` file which would give you the full server functionality and then you can run the compiled start script instead for production. One problem here -- I wouldn't be able to tell you how to add the option to modify require calls for avoiding relative imports i.e. `../../../some/distant/file`. Currently that is achieved through these lines:

https://github.com/tomatau/breko-hub/blob/master/scripts/helpers/babel.setup.js#L4-L6

As you can see, I'm using a library that needs requiring, and doing this from inside a .babelrc file isn't something I've spent much time trying to resolve.

I'd be happy to accept a modification to the build script or a new `build-sever` script that would make the production start command more efficient.

On the flip side - having the babel-register as it is isn't __sooo__ bad. All it will do is run-time compile the server as the command is initially run, from then on, it would be as if the server was running from compiled source code anyway! So not actually the biggest problem. I'm aware of a number of apps that are using the babel-register for their production servers.

**Comment by fishmacs** [comment]
Thanks for the reply!

I think you just require babel-register once in your start script, but it affects all js files, compiling them on the fly, of course, just once each file.

About relative imports, I failed on using babel-resolve-relative-module without babel-register. And I found this [babel-plugin-module-alias](https://github.com/tleunen/babel-plugin-module-alias) promising, which just sits in .babelrc, does not need another js. But I think I should have different aliases, then different .babelrc for development and production respectively.
  
By the way, breko hub still seems too complicated for my usage after several days' study, I'm working on my own boilerplate now. But breko hub gave me many insights of how to build a koa-react-webpack project, thanks!

**Comment by tomatau** [comment]
No problem!

That's right, it's just imported once and then compiles then on initialisation of the server. They are all already compiled by the time any requests come in to the server.

Hey - nice find on babel-plugin-module-alias! I will look into moving across to that as it looks a little cleaner, although the alias setup for each folder could be a bit of a hassle.  Also, not sure why you would want different aliases for production and dev? I always prefer to have a more consistent environment between dev and pub whilst aiming for a super nice developer experience.

I'm sorry to hear that breko-hub was too complicated!

Would you be able to share the areas that were complicated? I'd be really interested in knowing what could help!

My next step for this project is to go full time on documentation and making it easier to pick up -- so any areas to focus on would be great!

**Comment by fishmacs** [comment]
I think the js files are compiled only when they are used, that is what mean by "on-the-fly",  Not all get compiled while server starting?

About different aliases,  js files should be compiled to a directory like build/ if babel-register disabled. so a alias for development like ./src/app => app should be ./build/src/app => app for production. Or there can be another .babelrc under build/?

I said breko-hub complicated because I'm too new in front-end, I just have so much to learn: react, webpack, react-router, redux, history, store, action, hot-loading, isomorphic, socket.io, ......I've learned much from breko-hub and some other places, but I still feel overwhelmed when all these stuffs come to my brain together.....

So, I think the best choice is, writing my own project, just one thing one time. Maybe it woule be not so complicated after I got familiar with these concepts and implementations :)

**Comment by tomatau** [comment]
So, when the server is started, all of the files are 'required' to configure the server - so they will already be compiled and in memory by the time any requests come in. This is slightly different in development because of the server hot reloading... but in production they should be compiled during the server initialisation phase.

If the server code was to be pre-compiled, it would make sense to put it into a single bundle where the aliases would already be resolved. So the aliases should hold true for both dev and production.

Yes I totally agree, there is a huge amount of things to learn and I definitely agree that building things from the start up really helps!

Now a shameless plug, I've started writing a blog that discusses a number of techniques used by breko-hub (and the blog was actually made using breko-hub) that may help you understand a few of the techniques being used. Check it out https://tomatao-blog.herokuapp.com/.  It's a new blog, so not so many posts just yet, but I'm slowly building them up to cover many topics of universal/isomorphic apps and how breko-hub has addressed them.

**Comment by fishmacs** [comment]
Ok, I'll read the blog, it would be a great resource for learning! I plan to study hot loader in next step, and I saw an article about it in the blog, great!

I'm think if hot reloading available for production, do not need to restart server?

The author of [react-transform-hmr](https://github.com/gaearon/react-transform-hmr) said it is deprecated:

> _This_ Project Is Deprecated_
> 
> _React Hot Loader 3 is on the horizon, and you can try it today (boilerplate branch, upgrade example). It fixes some long-standing issues with both React Hot Loader and React Transform, and is intended as a replacement for both. The docs are not there yet, but they will be added before the final release. For now, this commit is a good reference._

**Comment by tomatau** [comment]
Hot reloading in production would not be recommended as it could introduce memory leaks quite easily in server code -- also you will need to push the whole code change to your production hosting which will call for a restart anyway. Most hosting does some form of A/B leg deployments so restarting the server is fine. If you want to persist memory state, you can run all of your server side actions through a message system and replay them on new server instances.

I'm watching the new react-hot-loader-3 very closely, it's in beta right now but I am planning to switch when it arrives. Although, the HMR transform is working well for breko hub as it is.

**Comment by fishmacs** [comment]
Ok, thanks your answer 👍 
Another question:
I'm trying hot reloading, seems webpack build ok:

> webpack Webpack compile started +0ms
>   webpack Webpack compiling +5ms
> webpack built a145ce8037f8cfec0c86 in 54ms

but I just can't find the output bundle file, in file system nor via URL, my webpack config below:

    entry: 'src/app/entry.js',
    output: {
      path: 'public',
      filename: 'bundle.js',
      publicPath: '/',
    }

**Comment by tomatau** [comment]
Are you using the webpack middleware for your server? That will compile the bundle to memory.

**Comment by fishmacs** [comment]
Got it. The webpack config entry did not accept 'src/app/entry.js', I changed it to full path, then it worked.
The koa-webpack-dev-middle's options is {quiet: true, noInfo: true, ...} in breko-hub, I set them to false, then the error message displayed and I figured it out :)
