### ISSUE TITLE
Problems with babel-polyfill and debug

### ISSUE THREAD

**Issue by nasushkov** [tomatau/breko-hub#32]
Hi, I'm trying this boilerplate for one of my personal projects. Two problems that I faced at the very beginning:

1. babel-polyfill works only when I explicitly call babel-register with presets like this:
  `require("babel-register")({
    presets: [ 'es2015', 'react', 'stage-0'],
    plugins: [
        "add-module-exports",
        "babel-root-import",
        "react-require",
        ["provide-modules", {
            "debug": "debug"
        }]
    ]
});` 
It seems that it ignores .babelrc. So how can I fix it without calling  require("babel-register") explicitely/

2. debug doesn't work with babel-polyfill. I tried various configurations (exact as in the boilerplate,  explicitly requiring debug), but it works only when I remove babel-polyfill at all. Any thoughts how to work around this?

Thanks.

**Comment by tomatau** [comment]
Hi - how are you starting this commands? Could you give me some repro steps as when I run `npm start` it works for me.

**Comment by nasushkov** [comment]
I simplified your code for my case So this one doesn't work:

`require('babel-polyfill');
const argv = require('yargs').argv;
const fileWithPath = (() => {
    switch(true) {        
        case argv.build:
            return './build.js';
        default:
        case argv.start:
            return '../app/server';
    }
})();
require(fileWithPath);`

And this works fine:
`require('babel-polyfill');
require("babel-register")({
    presets: [ 'es2015', 'react', 'stage-0'],
    plugins: [
        "add-module-exports",
        "babel-root-import",
        "react-require",
        ["provide-modules", {
            "debug": "debug"
        }]
    ]
});
const argv = require('yargs').argv;

const fileWithPath = (() => {
    switch(true) {        
        case argv.build:
            return './build.js';
        default:
        case argv.start:
            return '../app/server';
    }
})();

require(fileWithPath);`

Everything else is pretty same. Maybe it's because I'm running it on windows 10. 
The second problem is not valid anymore (I was too late to set DEBUG variable, my mistake)

**Comment by tomatau** [comment]
how are you starting this command? babel needs to know that it should be applied to the files still, so you would either need to compile it with babel or start using `babel-node`.

I prefer to use the babel-register in combination with a babelrc.

The problems you're facing aren't with this boilerplate as you've changed the boilerplate. Your problems are with using babel the way you expect to.
