### ISSUE TITLE
style init after js is loaded

### ISSUE THREAD

**Issue by ratik** [tomatau/breko-hub#35]
Hi
So there is issue in Chrome: styles are applied only after js loaded because classnames added into DOM.
Is there any way to fix the loading process so class names generated at server rendering phase are exact as in css bundle file? 

Thanks.

**Comment by tomatau** [comment]
This only happens in dev to enable CSS module hot reloads.

Make a production build and the styles are available immediately.

**Comment by tomatau** [comment]
To do the production build:

Change your `.env` file to have `NODE_ENV=production`

then:

`npm run build`

`npm start`

you'll see all styles are applied immediately.

**Comment by ratik** [comment]
thank you, it works like a charm
