### ISSUE TITLE
Webpack method deprecated

### ISSUE THREAD

**Issue by ravinpatel** [tomatau/breko-hub#36]
[webpack-isomorphic-tools] [error] `.development()` method is now deprecated (for server-side instance only, not for webpack plugin instance) and has no effect. Set up a proper `process.env.NODE_ENV` variable instead

^^^^ Got above when ran 'npm start' 

Many thanks love ur work bro, employ me

**Comment by tomatau** [comment]
fixed in https://github.com/tomatau/breko-hub/commit/04d85ef535bc0ddbdae180c010ec20dea1cdf829
