### ISSUE TITLE
Dynamic Routes

### ISSUE THREAD

**Issue by mclouvem** [tomatau/breko-hub#6]
Hi @tomatau! I've just clean clone this repo and I'm making some tests with dynamic routes(https://github.com/rackt/react-router/blob/master/docs/guides/advanced/DynamicRouting.md), but I'm having some hard times to figure it out how to implement it. Could you give some tips about it?

I know it is not an issue, but I couldn't find another way to contact you.
Thanks!

**Comment by tomatau** [comment]
Hey @mclouvem - I've never attempted dynamic routes myself but I assume that you'll need to provide a way for the server code to load routes if they match the request. So you might need something like this:

```js
if (typeof require.ensure !== "function") require.ensure = (d, c) => c(require)
```

**Comment by mclouvem** [comment]
Thanks @tomatau for this quick answer. I'm gonna try this. One last question... you mentioned an sample app using this starter kit, so do you have some sample that you can share? I'm quite newbie on redux stuff. 
I'm searching for a Koa starter kit, and yours seems really great.

**Comment by tomatau** [comment]
Hey @mclouvem -- sorry I don't have that ready yet. There's just the example FooRoute and HeadNavigation that give a bit of direction.

**Comment by mclouvem** [comment]
@tomatau...I made a simple example and it's working.

I was checking webpack's production settings and there is no compression set. There is a reason for it?

**Comment by tomatau** [comment]
Are you talking about the compression of assets sent from the server? Which version of breko hub are you using and how are you building production? I fixed an issue with asset compression a few weeks back.

**Comment by mclouvem** [comment]
Maybe you can add this to webpack settings

```javascript
new webpack.optimize.UglifyJsPlugin({
  compress: {
     screw_ie8: true, // eslint-disable-line camelcase
     warnings: false // Because uglify reports irrelevant warnings.
   }
})
```
I'm building production using npm run build && npm run start

**Comment by tomatau** [comment]
Want to PR it? Can just add the options to src/config/webpack.production.config.js

**Comment by mclouvem** [comment]
Yes! I'll submit it.
